### PR TITLE
Importance update

### PR DESCRIPTION
**Pull request by CoolDoctorWho**
This is useless. Utterly useless for it's penultimate goal, maybe it's ultimate will have this but this is useless in this script. It's short. Stubby. And stupid.

### CODE REVIEW

**Comment by Diitto** [comment]
Asdf

**Comment by Diitto** [comment]
FilteringEnabled shouldn't be a problem reinfgt.

**Comment by NetworkLabs** [comment]
I don't see any sort of statement in regards to FilteringEnabled...? The description was mainly a placeholder, and is no where near the real statement.

**Comment by NetworkLabs** [comment]
Hi there.

The following code will be fixed when we begin to rewrite Miracle to match the more professional standards. I had confusion on the purpose of ReplicatedStorage, and those confusions have now been resolved. Thank you for your concerns, however.

**Comment by Diitto** [comment]
Fewl. Lrn2Script.
fat fgt
lrrrrnnn222sccrrripppttt
There should be no reason for the client to get that data.
None at all.
The server should handle EVERYTHINGASDASDA.

**Comment by Diitto** [comment]
And haxxers are weak. k 
lrn2makemiracles
The data should *always* be held in ServerStorage.
Hell, if it's not used by other scripts, it should be held in nil. >.<

**Pull request closed without merging**
